name: base
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.0.2=py36_0
  - bokeh=1.0.2=py36_0
  - bzip2=1.0.6=h1de35cc_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2018.10.15=py36_0
  - cffi=1.11.5=py36h6174b99_1
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - click-plugins=1.0.4=py36_0
  - cligj=0.5.0=py36_0
  - conda=4.5.11=py36_0
  - conda-env=2.6.0=1
  - cryptography=2.3.1=py36hdbc3d79_0
  - curl=7.61.1=ha441bb4_0
  - cycler=0.10.0=py36hfc81398_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py36_0
  - descartes=1.1.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=h0a44026_0
  - fiona=1.7.12=py36h0dff353_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - freexl=1.0.5=h1de35cc_0
  - gdal=2.2.4=py36h6440ff4_1
  - geopandas=0.3.0=py36_0
  - geos=3.6.2=h5470d99_2
  - gettext=0.19.8.1=h15daf44_3
  - giflib=5.1.4=h1de35cc_1
  - glib=2.56.2=hd9629dc_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.2=hfa1e0ec_1
  - icu=58.2=h4b95b61_1
  - idna=2.7=py36_0
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.2.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=he5867d9_2
  - json-c=0.13.1=h3efe00b_0
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - kealib=1.4.7=h40e48e4_6
  - kiwisolver=1.0.1=py36h0a44026_0
  - krb5=1.16.1=h24a3359_6
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.61.1=hf30b1f0_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgdal=2.2.4=h7b1ea53_1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=h4e6abe9_2
  - libpng=1.6.35=ha441bb4_0
  - libpq=10.5=hf30b1f0_0
  - libsodium=1.0.16=h3efe00b_0
  - libspatialindex=1.8.5=h2c08c6b_2
  - libspatialite=4.3.0a=ha12ebda_19
  - libssh2=1.8.0=h322a93b_4
  - libtiff=4.0.9=hcb84e12_2
  - libuuid=1.0.3=h6bb4b03_2
  - libxml2=2.9.8=hab757c2_1
  - markupsafe=1.1.0=py36h1de35cc_0
  - matplotlib=3.0.1=py36h54f8f79_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36hb8a8100_0
  - mkl_random=1.0.1=py36h5d10147_1
  - munch=2.3.2=py36_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_0
  - notebook=5.7.2=py36_0
  - numpy=1.15.4=py36h6a91979_0
  - numpy-base=1.15.4=py36h8a80b8c_0
  - olefile=0.46=py36_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.0.2p=h1de35cc_0
  - packaging=18.0=py36_0
  - pandas=0.23.4=py36h6440ff4_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - patsy=0.5.1=py36_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.3.0=py36hb68e598_0
  - pip=18.1=py36_0
  - pixman=0.34.0=hca0a616_3
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.9=0
  - proj4=5.0.1=h1de35cc_0
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - psycopg2=2.6.2=py36_0
  - ptyprocess=0.6.0=py36_0
  - pycosat=0.6.3=py36h1de35cc_0
  - pycparser=2.19=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.3.0=py36_0
  - pyproj=1.9.5.1=py36h833a5d7_1
  - pyqt=5.9.2=py36h655552a_2
  - pysal=1.14.4.post1=py36_1
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.5=py36_0
  - python.app=2=py36_9
  - pytz=2018.7=py36_0
  - pyyaml=3.13=py36h1de35cc_0
  - pyzmq=17.1.2=py36h1de35cc_0
  - qt=5.9.6=h45cd832_2
  - qtconsole=4.4.2=py36_0
  - readline=7.0=h1de35cc_5
  - requests=2.20.1=py36_0
  - rtree=0.8.3=py36_0
  - ruamel_yaml=0.15.46=py36h1de35cc_0
  - scikit-learn=0.20.1=py36h4f467ca_0
  - scipy=1.1.0=py36h28f7352_1
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.6.2=py36_0
  - shapely=1.6.4=py36h20de77a_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.11.0=py36_1
  - sqlalchemy=1.2.14=py36h1de35cc_0
  - sqlite=3.25.3=ha441bb4_0
  - statsmodels=0.9.0=py36h1d22016_0
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.32.3=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xerces-c=3.2.2=h44e365a_0
  - xlrd=1.1.0=py36_1
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - future==0.17.1
    - progressbar2==3.38.0
    - pygam==0.8.0
    - python-utils==2.3.0
prefix: /Users/mukeharmon/miniconda

